export const FETCH_STORIES = 'FETCH_STORIES';
export const FETCH_STORIES_RELOAD = 'FETCH_STORIES_RELOAD';
export const FETCH_STORY = 'FETCH_STORY';
export const LOAD_STORIES = 'LOAD_STORIES';
export const RELOAD_STORIES = 'RELOAD_STORIES';
export const LOAD_STORY = 'LOAD_STORY';
